#!bash
_kite_completion() {
    COMPREPLY=( $( env COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   _KITE_COMPLETE=complete $1 ) )
    return 0
}

complete -F _kite_completion -o default kite;
